# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2015-2016.

branches:
  only:
    - master
    - develop

dist: trusty

language: cpp

notifications:
  email:
    recipients:
      - jhunold@gmx.eu

sudo: required

env:
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    - env: TOOLSET=clang-3.9
      os: linux
    - env: TOOLSET=clang-4.0
      os: linux
    - env: TOOLSET=clang-3.6
      os: linux
    - env: TOOLSET=gcc-4.7
      os: linux
    - env: TOOLSET=gcc-4.8
      os: linux
    - env: TOOLSET=gcc-4.9
      os: linux
    - env: TOOLSET=gcc-5.1
      os: linux
    - env: TOOLSET=gcc-6
      os: linux
    - env: TOOLSET=gcc-7
      os: linux
    - env: TOOLSET=xcode-7.3
      os: osx
      osx_image: xcode7.3
    - env: TOOLSET=xcode-8.3
      os: osx
      osx_image: xcode8.3

before_install:
  # Fetch the scripts to do the actual building/testing.
  - |
    wget "https://raw.githubusercontent.com/boostorg/regression/develop/ci/src/ci_boost_common.py" -P ..
    wget "https://raw.githubusercontent.com/boostorg/regression/develop/ci/src/ci_boost_library_test.py" -P ..

install: python "${TRAVIS_BUILD_DIR}/../ci_boost_library_test.py" install
before_script: python "${TRAVIS_BUILD_DIR}/../ci_boost_library_test.py" before_script
script: python "${TRAVIS_BUILD_DIR}/../ci_boost_library_test.py" script
after_success: python "${TRAVIS_BUILD_DIR}/../ci_boost_library_test.py" after_success
after_failure: python "${TRAVIS_BUILD_DIR}/../ci_boost_library_test.py" after_failure
after_script: python "${TRAVIS_BUILD_DIR}/../ci_boost_library_test.py" after_script
